# make sure to `git submodule update --init` before building images
version: "3"
services:
  web:
    restart: always
    image: coddingtonbear/intheam_web
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
      args:
        SUPERVISORD_CONFIG: ./docker/django/supervisord.conf
    links:
      - postgres:postgres
      - redis:redis
      - memcached:memcached
      - taskd:taskd
      - sse:sse
    env_file:
      - .env
      - .private.env
    volumes:
      - ./:/data/web
      - task-data:/task_data
      - django-static-assets:/django-static
    networks:
      - backend
  sse:
    restart: always
    image: coddingtonbear/intheam_sse
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
      args:
        SUPERVISORD_CONFIG: ./docker/django/supervisord.sse.conf
    expose:
      - "8001"
    links:
      - postgres:postgres
      - redis:redis
      - memcached:memcached
      - taskd:taskd
    env_file:
      - .env
      - .private.env
    volumes:
      - ./:/data/web
      - task-data:/task_data
    networks:
      - backend
  celery:
    restart: always
    image: coddingtonbear/intheam_celery
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
      args:
        SUPERVISORD_CONFIG: ./docker/django/supervisord.celery.conf
        CRONTAB: ./docker/django/celery.crontab
    links:
      - postgres:postgres
      - redis:redis
      - memcached:memcached
      - taskd:taskd
    env_file:
      - .env
      - .private.env
    ports:
      # - "25:8025"
      # Limit to localhost only:
      - "127.0.0.1:25:8025"
    volumes:
      - ./:/data/web
      - task-data:/task_data
    networks:
      - backend
  static-builder:
    image: coddingtonbear/intheam_static-builder
    build:
      dockerfile: ./docker/static-builder/Dockerfile
      context: ./
    environment:
      BUILD_MODE: development
    volumes:
      - ./ui:/app
      - static-assets:/app/dist
    env_file:
      - .env
      - .private.env
    networks:
      - backend
  nginx:
    restart: always
    image: coddingtonbear/intheam_nginx
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ./
    ports:
      # - "80:80"
      # - "443:443"
      # Limit to localhost only:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./docker/nginx/secrets:/certificates
      - static-assets:/app
      - django-static-assets:/django-static
    networks:
      - backend
    links:
      - web:web
      - static-builder:static-builder
  postgres:
    restart: always
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend
  redis:
    restart: always
    image: redis:latest
    networks:
      - backend
  memcached:
    image: "bitnami/memcached:latest"
    networks:
      - backend
  taskd:
    image: coddingtonbear/intheam_taskd
    build:
      dockerfile: ./docker/taskd/Dockerfile
      context: ./
    ports:
      # - "53589:53589"
      # Limit to localhost only:
      - "127.0.0.1:53589:53589"
    networks:
      - backend
    links:
      - redis:redis
    volumes:
      - taskd-data:/var/taskd/orgs
      - ./docker/taskd/secrets:/var/taskd/pki
  troubleshooting:
    image: "python:3.8-slim"
    volumes:
      - taskd-data:/taskd_data
      - task-data:/task_data
      - db-data:/db_data
volumes:
  db-data:
    external: true
  task-data:
    external: true
  taskd-data:
    external: true
  django-static-assets:
  static-assets:
networks:
  backend:
